version: "3.9"
   
services:
  redis_db:
    image: redis:alpine
    container_name: cache

  app:
    build: .
    command: "npm run dev:app"
    depends_on:
      - redis_db
    ports:
      - 3001:3001
    volumes:
      - ./:/code
      # really didn't like this for some reason 
      #- /tmp/books:/books
    environment:
      - REDIS_URL=redis://cache
      - PORT=3001
      - VIRTUAL_PORT=3001


  worker:
    build: .
    command: "npm run dev:worker"  
    depends_on:
      - redis_db
    volumes:
      - ./:/code
    environment:
      - REDIS_URL=redis://cache


