version: "3.9"
   
services:
  redis_db:
    image: redis:alpine
    container_name: cache

  app:
    build: .
    command: "npm run start:app"
    depends_on:
      - redis_db
    ports:
      - 3001:3001
    volumes:
      - booksvol:/books
    environment:
      - REDIS_URL=redis://cache
      - PORT=3001
      - BOOKSDIR=/books
      - VIRTUAL_HOST=epub-creator.vincentsaulys.com 
      - LETSENCRYPT_HOST=epub-creator.vincentsaulys.com 
      - VIRTUAL_PORT=3001
      - LETSENCRYPT_EMAIL=vincent@saulys.me 


  worker:
    build: .
    command: "npm run start:worker"  
    depends_on:
      - redis_db
    volumes:
      - booksvol:/books
    environment:
      - REDIS_URL=redis://cache
      - BOOKSDIR=/books

volumes:
  booksvol:


