version: "3.9"
   
services:
  cache:
    image: redis:alpine

  app:
    build: .
    command: "npm run dev:app"
    depends_on:
      - cache
    ports:
      - 3001:3001
    volumes:
      - ./:/code
    environment:
      - REDIS_URL=redis://cache
      - PORT=3001
      - VIRTUAL_PORT=3001


  worker:
    build: .
    command: "npm run dev:worker"  
    depends_on:
      - cache
    volumes:
      - ./:/code
    environment:
      - REDIS_URL=redis://cache


